### PR TITLE
Indianapolis City Council

### PR DESCRIPTION
**Pull request by haileyhoyat**
@jamesturk 

Hi James, this is Hails from City Bureau. I am working on a scraper for this calendar and I'm struggling with the concept of extracting data from a dynamically loaded web page. I think all the data is on the page because you can filter on different criteria (ex: for the month, for the year, for the next 180 days). But I'm not sure how to get that data. 

Do you have any guidance on this matter?  Thanks. 

p.s. I promise I value you way more than simply the guy I ask for help and who is generous enough to always help me. 

https://calendar.indy.gov/

### CODE REVIEW

**Comment by jamesturk** [comment]
Hi!

Sorry hadn't gotten to your email yet, I took a look at the page and do think it is being dynamically loaded, here's the approach I take:

1) Open the page and then right click->view-source to view the source (view-source:https://calendar.indy.gov/)
   This method shows you the exact HTML the server returns so you can search through it for a key phrase (I used anniversary since it was in an event name)-- from here it looked like that content was *not* in the initial page load, meaning it must be a later request.

2) That leads me to use the Network tab of devtools, which I opened to observe that there was an XHR request being made to load more data. (screenshot attached, note I'm on Network w/ XHR selected to limit to those)

There's a single request, which I can look at the response and see that it does indeed contain HTML with the events.  I think you'll need to figure out how to make those requests directly, pages look something like this:

`https://calendar.indy.gov/handlers/query.ashx?tenant=&site=&get=eventlist&page=0&pageSize=-1&total=-1&view=grid.xslt&&_=1690307402685`

Let me know if I can help clarify anything further, but hopefully this points you in the right direction!

**Comment by haileyhoyat** [comment]
Hello! @jamesturk 

Thank you, this was very helpful. I am able to recreate the steps you mentioned and I do see the html. For example here is the response html for a request for the next 180 days, which I can prove because the html includes days for the 2024 year. 

https://calendar.indy.gov/handlers/query.ashx?tenant=&site=&get=eventlist&page=0&pageSize=-1&total=-1&view=grid.xslt&callback=jQuery191021030257109264605_1690320102038&_=1690320102039

Do you remember how scraping Google stuff is not a good idea? This calendar below I think is not a google calendar but rather is connected to an ad tool google uses. I came to this conclusion by doing the Network tab steps to see the request if I were to move the calendar to August, for example. I get various urls that are not html urls but rather like...tools for a google ad tool. Have you ever seen something like that before? Ultimately I am looking for the most reliable way to retrieve the html and even the url that changes when I change the month does not seem to be reliable (i.e. can't find like a predictable pattern to it).

https://www.accesskent.com/Calendar/calChangeActionE.do?from=events&type=&subtractMonth=Y&calMonth=08&calYear=2023

**Comment by haileyhoyat** [comment]
@rhetr Hi. This is Hails. We worked together last summer for the city builds with James Turk. Do you have experience scraping data from dynamically loaded webpages? I am scraping the below webpage. When I filter for the 'Next 180 Days', and then look at the XHR request made on the page, I do see the url containing the html (link to the web page linked below).

Have you ever made a POST request using Python before (I'm guessing I need to make a POST request to get the url? Is that even the right thing to do here? When inputing the url to scrapy it returns a .txt file containing the html. Any words of advice would be greatly appreciated. 

https://calendar.indy.gov/

[XHR request](https://calendar.indy.gov/handlers/query.ashx?tenant=&site=&get=eventlist&page=0&pageSize=-1&total=-1&view=grid.xslt&callback=jQuery191021030257109264605_1690320102038&_=1690320102039)

**Comment by rhetr** [comment]
hey Hails, I can't recall if I've done any dynamically loaded pages. [here](https://docs.scrapy.org/en/latest/topics/dynamic-content.html) are some options, though i think you may be onto something with the XHR stuff. but when I try to open the XHR request i get `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` so it seems like the request might need to be cleaned up a bit to run properly.

i did deal with a webpage that required a cookie from a previous page, which i dealt with using [`response.follow`](https://github.com/City-Bureau/city-scrapers-atl/blob/main/city_scrapers/spiders/atl_dekalb_county_boc.py#L40); i think you can set [`method='POST'`](https://docs.scrapy.org/en/latest/topics/request-response.html?highlight=.follow#scrapy.http.Response.follow) to make a POST request too.

**Comment by haileyhoyat** [comment]
@rhetr Thanks so much. Last question. 

Below is a calendar for County Commissioner. I'm experimenting in Scrapy shell. I know all the relevant html is retrieved back because I can see the html via the command 'view(response)'. However, the deepest I'm able to drill down into the html is the command  'response.css('main div').get()'. When I try to add on more html elements Scrapy doesn't return anything. I find it odd because I know all the html is there; it's almost like Scrapy doesn't see anything past that level in the DOM. 

Have you ever run into something like this where the html is present but Scrapy isn't drilling down?

https://www.indy.gov/activity/county-commissioners-meeting-schedule

**Comment by rhetr** [comment]
this looks like a js app to me--see the html


    <main role="main" id="main">
    <div id="app" activity_id="county-commissioners-meeting-schedule"></div>
    </main>
    <footer id="footer"></footer>

      <script src="/js/common-f3385853b66ef3f0c32e540cba59087f.js?vsn=d"></script>
      <script src="/js/vendor-97e6489ae9304f36bd2722970ba10dce.js?vsn=d"></script>
      <script src="/js/header-18193a5b45d76ba179c8087453e9856f.js?vsn=d"></script>

**Comment by haileyhoyat** [comment]
@rhetr ah, ok, good catch. so does that mean this won't be a straight forward scrape? like it does page requests and whatnot?

**Comment by rhetr** [comment]
i believe so!

**Pull request closed without merging**
